=== JaimeRamirez777/UD_LMSGI/u4/Ejercicio1/biblioteca.dtd
<!DOCTYPE biblioteca [
  <!ELEMENT biblioteca (libro+)>
  <!ELEMENT libro (titulo, autor, año, isbn, genero)>
  <!ELEMENT titulo (#PCDATA)>
  <!ELEMENT autor (#PCDATA)>
  <!ELEMENT año (#PCDATA)>
  <!ELEMENT isbn (#PCDATA)>
  <!ELEMENT genero (#PCDATA)>
]>

=== JaimeRamirez777/UD_LMSGI/u4/Ejercicio1/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
  <libro>
    <titulo>El Quijote</titulo>
    <autor>Miguel de Cervantes</autor>
    <año>1605</año>
    <isbn>978-3-16-148410-0</isbn>
    <genero>Novela</genero>
  </libro>
  <libro>
    <titulo>1984</titulo>
    <autor>George Orwell</autor>
    <año>1949</año>
    <isbn>978-0-452-28423-4</isbn>
    <genero>Distopía</genero>
  </libro>
  <libro>
    <titulo>Fahrenheit 451</titulo>
    <autor>Ray Bradbury</autor>
    <año>1953</año>
    <isbn>978-0-7432-4722-1</isbn>
    <genero>Distopía</genero>
  </libro>
  <libro>
    <titulo>Cien años de soledad</titulo>
    <autor>Gabriel García Márquez</autor>
    <año>1967</año>
    <isbn>978-0-06-088328-7</isbn>
    <genero>Realismo Mágico</genero>
  </libro>
  <libro>
    <titulo>El Gran Gatsby</titulo>
    <autor>F. Scott Fitzgerald</autor>
    <año>1925</año>
    <isbn>978-0-7432-7356-6</isbn>
    <genero>Novela</genero>
  </libro>
  <libro>
    <titulo>Orgullo y prejuicio</titulo>
    <autor>Jane Austen</autor>
    <año>1813</año>
    <isbn>978-0-14-143951-8</isbn>
    <genero>Romántico</genero>
  </libro>
  <libro>
    <titulo>Donde viven los monstruos</titulo>
    <autor>Maurice Sendak</autor>
    <año>1963</año>
    <isbn>978-0-06-443178-1</isbn>
    <genero>Infantil</genero>
  </libro>
  <libro>
    <titulo>El señor de los anillos</titulo>
    <autor>J.R.R. Tolkien</autor>
    <año>1954</año>
    <isbn>978-0-345-33968-3</isbn>
    <genero>Fantasía</genero>
  </libro>
  <libro>
    <titulo>Harry Potter y la piedra filosofal</titulo>
    <autor>J.K. Rowling</autor>
    <año>1997</año>
    <isbn>978-0-545-01022-1</isbn>
    <genero>Fantasía</genero>
  </libro>
  <libro>
    <titulo>El Código Da Vinci</titulo>
    <autor>Dan Brown</autor>
    <año>2003</año>
    <isbn>978-0-385-50420-8</isbn>
    <genero>Thriller</genero>
  </libro>
</biblioteca>
